# User config
author: "Nik Kim"
tagline: "Gaming AI"
description: "I am fascinated by the potential of advanced AI technologies and algorithms to create interactive and collaborative machine agents that replicate magic of gaming experiences that lies in the shared moments of adventure."
keywords: "Game, Video Game, AI, ML, RL"
email: "nnkim@andrew.cmu.edu"
ml_blog: "https://nik-pitts.github.io/machinelearning601/"
resume: "https://nik-pitts.github.io/"
github: "https://github.com/nik-pitts"

# Site config
baseurl: "/knocknocknik"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
